### ISSUE TITLE
Collection of bugs i faced

### ISSUE THREAD

**Issue by AISLVE** [crissNb/Dynamic-Island-Sketchybar#46]
Device: Macbook Air (M2, 15")

**Currently configuring**

First of all the music is **sometimes** not displayed correctly, logs here

LOGS:
**cat: /Users/dharya/.config/dynamic-island-sketchybar/scripts/islands/music/data/cache: No such file or directory
cat: /Users/dharya/.config/dynamic-island-sketchybar/scripts/islands/music/data/cache: No such file or directory
cat: /Users/dharya/.config/dynamic-island-sketchybar/scripts/islands/music/data/cache: No such file or directory
Terminated: 15
cat: /Users/dharya/.config/dynamic-island-sketchybar/scripts/islands/music/data/cache: No such file or directory
Terminated: 15
Terminated: 15**

Others incoming

**Comment by AISLVE** [comment]
<img width="1710" alt="Screenshot 2023-09-25 at 18 37 58" src="https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/4149d3da-893b-4dcb-ad5b-9231d43ee2a7">

**Comment by AISLVE** [comment]
<img width="837" alt="Screenshot 2023-09-25 at 18 42 22" src="https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/dd9d9a4e-fe9c-4936-9905-3eb065c551c1">
Also this is what the highest level of brightness looks like on it, any way to fix or modify it?

**Comment by AISLVE** [comment]
[https://we.tl/t-Mh90dB5X6c](url)

**Comment by crissNb** [comment]
> First of all the music is sometimes not displayed correctly, logs here

Missing cache file is an interesting bug to me. The dynamic island never removes the cache file. In other words, the error should only come up in the first time when you launch the dynamic island (as the cache file will be created afterwards).

> Also this is what the highest level of brightness looks like on it, any way to fix or modify it?

This is something I've hardcoded into the dynamic island and forgot to make it configurable. I will be making this change soon. For now, if you'd like to configure it anyway, you'll need to modify [volume_island.sh](https://github.com/crissNb/Dynamic-Island-Sketchybar/blob/main/scripts/islands/volume/volume_island.sh) manually (or brightness_island.sh). At line 54:

```bash
barWidth=$(bc -l <<<"$volume/100*240")
```

the `240` represents the width of the maximum volume bar. Again, I will be making it so that this value isn't hard coded soon.

> Also once i go to my fullscreen window and change sound, it doesn't show in dynamic island(nothing shows up, just the static notch)...

I'm not sure if this is something that is worth looking into. Because this project relies on sketchybar entirely, I'm not certain if this problem is happening to this specific config files for sketchybar or the sketchybar software itself (it is also likely that I may have not read the sketchybar documentation properly to resolve this issue). I will be trying, but I can't make any promises on this fix, as I don't really have any ideas on how to fix this problem.

From the video recording you've provided, I've also noticed that multiple islands seems to be colliding together, which shouldn't be happening. It looks like the helper program isn't functioning properly. I can't tell if this is because of the new macOS version or if this is just a problem in general, though. I'll be looking into this for certain as well this weekend.

**Comment by AISLVE** [comment]
I am on macos 14 public beta, might be because of that too

**Comment by crissNb** [comment]
Are you talking about the scale of the artwork? If that's the case, it's definitely possible to implement. If you can, could you maybe provide a design you're thinking of? I personally wasn't entirely fan of the current music island design either.

**Comment by AISLVE** [comment]
Okay, time for some photoshop, you will have to wait for some time tho

**Comment by AISLVE** [comment]
![Screenshot 2023-09-26 at 17 55 15](https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/e2fab3fe-5ac7-444f-bf51-18a7d2bc54c1)
like the artwork should be somewhat like like the playlists and the font even i am not sure about

**Comment by AISLVE** [comment]
there are two options, one being right next to the thumbnail, and one in center

**Comment by AISLVE** [comment]
![Screenshot 2023-09-26 at 17 58 44](https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/900d910c-f87f-41ed-a9a2-cb3eb65e3fce)
one is somewhat like this

**Comment by AISLVE** [comment]
ofc, the border radius is there too, but i think you get the idea

**Comment by AISLVE** [comment]
![Screenshot 2023-09-26 at 18 04 52](https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/6408090b-ca46-40ed-9622-86f966ebcb76)
is it fixable, not that big of a deal but a qol feature @crissNb

**Comment by AISLVE** [comment]
> Also once i go to my fullscreen window and change sound, it doesn't show in dynamic island(nothing shows up, just the static notch) but when i come back and change it it's blank, only the animation would be shown and sometimes it totally breaks

this seems to be fixed now, but a new issue appears where the app that i have switched to isn't recognized for the first time

**Comment by AISLVE** [comment]
@crissNb now that i see the video, is it slowed down or is my mac speeding it up

**Comment by crissNb** [comment]
The latest commit should cover most of the things that has been discussed in this issue. As for the better music display, I couldn't get it to mask out with the rounded corners, so that's a bit unfortunate. Closing for now.

**Comment by AISLVE** [comment]
![Screenshot 3](https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/0b7eef41-79b2-42ef-b6bc-410458489023)
@crissNb

**Comment by AISLVE** [comment]
i have pulled the changes too
