### ISSUE TITLE
GUI 

### ISSUE THREAD

**Issue by AISLVE** [crissNb/Dynamic-Island-Sketchybar#57]
Any plans for a GUI version of the app?

**Comment by crissNb** [comment]
There are no plans yet, as this project is basically just configurations for sketchybar software.

**Comment by jacobmac2003** [comment]
> Any plans for a GUI version of the app?

For anyone interested, there's another app called Media Mate that adds the Dynamic Island and some interesting media control user interfaces that are far better than the default macOS ones. It's paid for and I use it, but I'd recommend to support the developer of this as much as possible if you do plan to use Media Mate, since open source projects are an important part of the future of software development.

**Comment by crissNb** [comment]
If in any case anyone's interested in GUI version of the app, here's alternative: https://fluidnoti.vercel.app/
