### ISSUE TITLE
More modular structure

### ISSUE THREAD

**Issue by cagdassalur** [crissNb/Dynamic-Island-Sketchybar#9]
What do you think about having a more modular structure and making it easier to get updates? 
I was thinking maybe everything can live inside plugins/Dynamic-Island-Sketchybar so we can just do a `git pull` in there and get everything up to date.
Maybe have 2 scripts to source `dynamic_island_setup.sh` and `dynamic_island_item.sh` with setup containing similar stuff to what's inside the example 'sketchybarrc' even containing defaults and such, user can override in their own skeychybar of course. Setup would be sourced before everything and item can be sourced in it's usual place.

I can make a pr for this and we can discuss further there if this makes sense, otherwise please feel free to close this

**Comment by cagdassalur** [comment]
We can get notification db path from an env variable inside `sketchybarrc` also so user don't have to modify inside the plugin. 
Also maybe some options in a similar way to enable/disable certain islands

**Comment by crissNb** [comment]
I think it would be great addition. I believe we can have everything in `plugins/Dynamic-Island-SketchyBar` as you said, and just do git pull every time a user wants to perform an update. Do you think config files should be in .gitignore? It makes sense on the one hand, but at the same time I suspect there will be breaking changes to config files (especially at the moment, as the dynamic island is in heavy development).

I can imagine it would be very convenient if the user only needs to source one single file from sketchybarrc. However, properties like bar size of the SketchyBar must remain a set value (otherwise it would break). I'm not sure how compatible overriden settings will be. If we can make dynamic island not rely on the bar size, it would be great.
As for the defaults, I was thinking of even just putting all the properties necessary directly to individual modules (so not having defaults at all). I believe some islands are already independent from the default settings of SketchyBar at the moment.

> We can get notification db path from an env variable inside sketchybarrc also so user don't have to modify inside the plugin.

Yeah, I definitely agree. Perhaps we can just use the following command (from README.md):
`lsof -p $(ps aux | grep -m1 usernoted | awk '{ print $2 }')| awk '{ print $NF }' | grep 'db2/db$' | xargs dirname`

> Also maybe some options in a similar way to enable/disable certain islands

This is something I'm definitely thinking of implementing. Because the island events are essentially just SketchyBar items, it shouldn't be too difficult to implement. Perhaps this can come with more modular structure + configs.

**Comment by cagdassalur** [comment]
>  Do you think config files should be in .gitignore? It makes sense on the one hand, but at the same time I suspect there will be breaking changes to config files (especially at the moment, as the dynamic island is in heavy development).

I was imagining users having their own config if they prefer, leaving the structure to them (either by sourcing their own config or defining stuff in sketchybarrc), otherwise the plugin will just use defaults. This should handle breaking changes as well imo, they may just update some of their own config with some changes

> I can imagine it would be very convenient if the user only needs to source one single file from sketchybarrc. However, properties like bar size of the SketchyBar must remain a set value (otherwise it would break). I'm not sure how compatible overriden settings will be. If we can make dynamic island not rely on the bar size, it would be great.

I was thinking having this kind of setup:
```bash
# sketchybarrc
source './plugins/DynamicIsland/setup.sh' # handling all setup and default vars

sketchybar -m --bar \
    height=40 \
    position=top \

# user items and config

source './plugins/DynamicIsland/item.sh' #loading the actual item

sketchybar -m --update

echo "sketchybar configuration loaded.."


```

This way plugin shouldn't mess with user defined values, and setting them only if they haven't defined it after the setup script. I have a similar setup right now, where i run an automated script when i connect an external screen to have a different bar height, island also works fine.  Does this make sense for you?

Other stuff you describe are great points, it'll be nice to have them eventually.

I'll try some things out and create a pr when i have some free time

**Comment by cagdassalur** [comment]
created #10
